In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [43]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/kaggle/input/fake-news/train.csv")

In [4]:
df.shape

(20800, 5)

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [11]:
df=df.dropna()

In [12]:
df.shape

(18285, 5)

In [15]:
x=df.drop("label",axis=1)

In [16]:
y=df["label"]

In [18]:
print("X shape:",x.shape)
print("Y shape:",y.shape)

X shape: (18285, 4)
Y shape: (18285,)


In [19]:
import tensorflow as tf
tf.__version__

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: l

'2.12.0'

Tensorflow Libraries

In [22]:
from tensorflow.keras .layers import Embedding #word2vec
from tensorflow.keras.preprocessing.sequence import pad_sequences #converting all sentence of equal length
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM , Dense


In [23]:
voc_size=5000

In [24]:
msg=x.copy()

In [25]:
msg.reset_index(inplace=True)

In [26]:
import nltk
import re #regular expression
from nltk.corpus import stopwords

In [27]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [36]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(msg)):
    review=re.sub('[^a-zA-Z]',' ',msg['title'][i]) # removing all special character expect alphabets
    review=review.lower()
    review=review.split()
    # if words are not present in english stop words stem it
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=" ".join(review)
    corpus.append(review)

In [37]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [38]:
ohe_rep=[one_hot(words,voc_size) for words in corpus]
ohe_rep

[[2579, 3619, 1860, 293, 609, 4604, 3603, 1841, 4556, 4165],
 [2045, 4537, 2566, 4483, 870, 3003, 3180],
 [4930, 3920, 4257, 4344],
 [865, 3750, 2008, 4270, 4926, 3004],
 [689, 870, 1597, 1962, 2355, 2325, 870, 1099, 3167, 3684],
 [4188,
  28,
  4965,
  509,
  2397,
  3582,
  1451,
  3129,
  569,
  228,
  1400,
  1786,
  3506,
  4696,
  3180],
 [3942, 4473, 3557, 1045, 2659, 1667, 4470, 2043, 281, 3249, 2973],
 [1044, 4533, 4146, 3915, 3116, 2861, 3582, 361, 281, 3249, 2973],
 [3547, 4570, 2409, 722, 1190, 4951, 468, 1042, 3582, 374],
 [1104, 3087, 176, 600, 4713, 4174, 2252, 4672],
 [3381, 2084, 2521, 4471, 2572, 4785, 4306, 3237, 3913, 396, 4223],
 [4270, 4003, 609, 4951, 3582, 3116],
 [74, 2453, 3618, 4390, 2404, 672, 891, 3586, 885],
 [4845, 2240, 2149, 970, 3961, 1583, 80, 281, 3249, 2973],
 [28, 3423, 2862, 1209, 1707, 281, 3249, 2973],
 [2553, 920, 1940, 1371, 4688, 1215, 2956, 4737, 3276, 2410],
 [354, 354, 4537],
 [3252, 4937, 4223, 532, 3582, 779, 48, 3180],
 [4160, 463, 2566

In [39]:
sent_length=20
embed=pad_sequences(ohe_rep,maxlen=sent_length,padding="pre")
print(embed)

[[   0    0    0 ... 1841 4556 4165]
 [   0    0    0 ...  870 3003 3180]
 [   0    0    0 ... 3920 4257 4344]
 ...
 [   0    0    0 ...  281 3249 2973]
 [   0    0    0 ... 2510  329 1407]
 [   0    0    0 ... 3899 3790 4428]]


In [41]:
embed_vector_feature=40
model=Sequential()
model.add(Embedding(voc_size,embed_vector_feature,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid')) #classification
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [44]:
x_final=np.array(embed)
y_final=np.array(y)

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.2,random_state=42)

In [48]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=11,batch_size=80)

Epoch 1/11
183/183 [==============================] - 10s 40ms/step - loss: 0.3364 - accuracy: 0.8490 - val_loss: 0.2054 - val_accuracy: 0.9106
Epoch 2/11
183/183 [==============================] - 7s 37ms/step - loss: 0.1439 - accuracy: 0.9459 - val_loss: 0.2002 - val_accuracy: 0.9163
Epoch 3/11
183/183 [==============================] - 7s 38ms/step - loss: 0.1075 - accuracy: 0.9623 - val_loss: 0.2336 - val_accuracy: 0.9150
Epoch 4/11
183/183 [==============================] - 7s 37ms/step - loss: 0.0881 - accuracy: 0.9673 - val_loss: 0.2758 - val_accuracy: 0.9111
Epoch 5/11
183/183 [==============================] - 7s 37ms/step - loss: 0.0734 - accuracy: 0.9745 - val_loss: 0.2790 - val_accuracy: 0.9117
Epoch 6/11
183/183 [==============================] - 7s 37ms/step - loss: 0.0525 - accuracy: 0.9835 - val_loss: 0.3047 - val_accuracy: 0.9128
Epoch 7/11
183/183 [==============================] - 7s 38ms/step - loss: 0.0351 - accuracy: 0.9893 - val_loss: 0.3517 - val_accuracy: 0.907

In [49]:
y_pred=model.predict(x_test)

115/115 [==============================] - 1s 7ms/step


In [54]:
y_pred=np.where(y_pred>0.5,1,0)
# 1 -it is a fake news
#0-it isn't a fake news

In [55]:
from sklearn.metrics import confusion_matrix


In [56]:
confusion_matrix(y_test,y_pred)

array([[1878,  204],
       [ 126, 1449]])

In [57]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9097621000820345


In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92      2082
           1       0.88      0.92      0.90      1575

    accuracy                           0.91      3657
   macro avg       0.91      0.91      0.91      3657
weighted avg       0.91      0.91      0.91      3657

